// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-5ypAAF8uJ0FwQrL2Pk15Mp8ubvSoLY',
    appId: '1:896335817043:web:6b66eb50a34a9acdedd9a6',
    messagingSenderId: '896335817043',
    projectId: 'tribb-829ca',
    authDomain: 'tribb-829ca.firebaseapp.com',
    storageBucket: 'tribb-829ca.appspot.com',
    measurementId: 'G-ZCSR0FC1V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5g6x333O2C3gac98-oZ7vP8pNF7h7NK0',
    appId: '1:896335817043:android:e4ab76c0f04aba23edd9a6',
    messagingSenderId: '896335817043',
    projectId: 'tribb-829ca',
    storageBucket: 'tribb-829ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzTp2Wm7CHi7d72crbkbdT_3AfUMF1X0k',
    appId: '1:896335817043:ios:8be758c861c9a8ccedd9a6',
    messagingSenderId: '896335817043',
    projectId: 'tribb-829ca',
    storageBucket: 'tribb-829ca.appspot.com',
    iosBundleId: 'com.cloudcertitude.tribb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzTp2Wm7CHi7d72crbkbdT_3AfUMF1X0k',
    appId: '1:896335817043:ios:b03ece86f0d8d699edd9a6',
    messagingSenderId: '896335817043',
    projectId: 'tribb-829ca',
    storageBucket: 'tribb-829ca.appspot.com',
    iosBundleId: 'com.cloudcertitude.tribb.RunnerTests',
  );
}
